--Auto-generated by code, all changes will be lost.
print("\n-LOG- Logger initialization started. Loading config...")
LOGGER = {
	config = {
		enabled = true,
		writetofile = true,
	},
	logfiles = {},
	
}

function LOGGER.ply(ply)
	if not ply then
		return "<none>"
	end
	if ply.SteamName then
		return ply:SteamName() .. "(" .. ply:Nick() .. ")(" .. ply:SteamID() .. ")"
	end
	return ply:Nick() .. "(" .. ply:SteamID() .. ")"
end
function LOGGER.team(n)
	if RPExtraTeams and RPExtraTeams[n] then
		return RPExtraTeams[n].name .. "[" .. n .. "]"
	end
	return "[" .. n .. "]"
end
AddCSLuaFile("logger_config.lua")
include("logger_config.lua")
print("\t-LOG- Config loaded. Loading modules...")
local files, folders = file.Find("logger/*", "LUA")
for k, v in pairs(files) do
	print("\t\t" .. v)
	if string.sub(v, 1, 3) == "cl_" then
		if SERVER then
			AddCSLuaFile("logger/" .. v)
		end
		if CLIENT then
			include("logger/" .. v)
		end
	elseif string.sub(v, 1, 3) == "sh_" then
		if SERVER then
			AddCSLuaFile("logger/" .. v)
		end
		include("logger/" .. v)
	elseif string.sub(v, 1, 3) == "sv_" then
		if SERVER then
			include("logger/" .. v)
		end
	end
end
print("-LOG- Modules loaded. Logger initialization complete.\n")